### ISSUE TITLE
remove empty content from `/#/info` page

### ISSUE THREAD

**Issue by alexissmirnov** [dialoguemd/covid-19#194]
https://covid19.dialogue.co/#/info 

Remove
- [ ] Information below applies to:
- [ ] Doesn’t apply to you?
- [ ] Get personalized info
- [ ] No results provided in URL.
- [ ] Get personalized info

The page should have only the title and the chatbot window inviting users to ask a question.

**Comment by jghosn** [comment]
Hi,

I just spoke with Alexis. Here are my suggestions to clean the page.

Remove:
COVID-19: What you need to know
Information below applies to:
Doesn’t apply to you?
Get personalized info
No results provided in URL.
Get personalized info

Replace with text explaining the context of the project. Here's my suggestion:
* English: "We are soliciting questions from Quebec's population related to the COVID-19 pandemic. Those questions will be used to help the Government of Québec refine and augment their FAQ related to the pandemic. Please type all questions that you have. Your help is needed and greatly appreciated."
* French: "Nous sollicitons les questions de la population québécoise en lien avec la pandémie COVID-19. Ces questions serviront à aider le gouvernement du Québec à améliorer et enrichir son système de questions/réponses relié à la pandémie. Veuillez écrire toutes les questions que vous avez. Votre aide est nécessaire et grandement appréciée."

Replace:
Do you have another question about COVID-19?
We review each question, and will update the FAQ when answers become available.
And the yes/no buttons

With a mechanism to type a first question with the text:
"Please type a question"
Once the question is typed, you can have:
"Do you have another question?" with yes/no buttons.

If the user says "no", you can say "Thank you for your help".

In French, you will have:
"Svp écrivez une question".

Then "Avez-vous une autre question?" with oui/non buttons.

If the user says "non", you can say "Merci pour votre aide."

Please let me know when the changes are done so that I can verify the page. Thanks.

**Comment by alexissmirnov** [comment]
Spoke to @jghosn, let's make these changes work not only for Quebec:

English: "We are soliciting questions related to the COVID-19 pandemic. Those questions will be used to help us refine and augment the FAQ and this chatbot related to the pandemic. Please type all questions that you have. Your help is needed and greatly appreciated."
French: "Nous sollicitons des questions relatives à la pandémie COVID-19. Ces questions seront utilisées pour nous aider à affiner et à compléter la FAQ et ce chatbot sur la pandémie. Veuillez taper toutes les questions que vous avez. Votre aide est nécessaire et grandement appréciée."

**Comment by vicrep** [comment]
Thank you for the feedback, @jghosn , I've created a new issue to update the bot flow so issues remain properly scoped :) The rest (clean up of page) will be fixed through this issue.

https://github.com/dialoguemd/covid-19/issues/202

**Comment by alexissmirnov** [comment]
Nous sollicitons des questions relatives à la pandémie COVID-19. Ces questions seront utilisées pour nous aider à affiner et à compléter la FAQ et ce chatbot sur la pandémie. Veuillez taper toutes les questions que vous avez. Votre aide est nécessaire et grandement appréciée.

**Comment by alexissmirnov** [comment]
We are soliciting questions related to the COVID-19 pandemic. Those questions will be used to help us refine and augment the FAQ to the pandemic. Please type all questions that you have. Your help is needed and greatly appreciated.

**Comment by jghosn** [comment]
And for french:
Nous sollicitons des questions relatives à la pandémie COVID-19. Ces questions seront utilisées pour nous aider à affiner et à compléter la FAQ sur la pandémie. Veuillez taper toutes les questions que vous avez. Votre aide est nécessaire et grandement appréciée."
